### ISSUE TITLE
Bug with Visual Workbench mod

### ISSUE THREAD

**Issue by SabsRat** [pnk2u/More-Smithing-Tables#1]
![image](https://github.com/user-attachments/assets/46cac52c-b3d0-41de-bb7d-a35974cfac22)
![image 2](https://github.com/user-attachments/assets/1eb3e1c5-df9e-45c5-b881-31c00e07a71d)
the og smithing table works fine its the varients in this mod that act like a crafting table
dont know if its your mod or theirs
fabric loader and most recent mod verison

**Comment by pnk2u** [comment]
Hey, thanks for reporting this incompatibility, I added compatibility for Visual Workbench in version 1.1.0 that I just uploaded on Modrinth and Curseforge. (Note that you might need to mine and place the Smithing Table anew for the update to properly take effect.) Please let me know if there is any further issues and if it has now been resolved, feel free to close this issue.
